project_id = "blwwpvvdnpkipjgajwiw"

[functions.get-taxonomy]
verify_jwt = false

[functions.get-business-models]
verify_jwt = false

[functions.classify-company]
verify_jwt = false

[functions.scrape-carbon-brief]
verify_jwt = false

[functions.scrape-iea-sources]
verify_jwt = false

[functions.classify-company]
verify_jwt = false

[functions.analyze-signal-themes]
verify_jwt = false

[functions.map-signals-to-theme]
verify_jwt = false

[functions.populate-theme-signals]
verify_jwt = false

[functions.populate-dashboard-theme-signals]
verify_jwt = false

[functions.populate-sources-from-signals]
verify_jwt = false