-- Add remaining framework criteria for categories B, C, D, E

-- Category B: Investability criteria
INSERT INTO public.framework_criteria (category_id, name, code, description, objective, weight, display_order, scoring_rubric, ai_prompt) VALUES
((SELECT id FROM public.framework_categories WHERE code = 'B'), 'Market Fragmentation', 'B1', 'Assessment of market concentration and competitive landscape', 'To evaluate if the market structure enables platform players to gain significant market share.', 33.33, 1, '{"1": {"label": "Consolidated", "description": "Top 5 players control >70% market share"}, "3": {"label": "Moderately Fragmented", "description": "Top 5 players control 30-70% market share"}, "5": {"label": "Highly Fragmented", "description": "Top 5 players control <30% market share"}}', 'What is the current market concentration in this sector? Who are the top players and what market share do they hold? What are the barriers to market consolidation?'),

((SELECT id FROM public.framework_categories WHERE code = 'B'), 'Investment Target Quality', 'B2', 'Availability and quality of potential investment targets in the space', 'To assess whether there are sufficient high-quality companies available for investment at different stages.', 33.33, 2, '{"1": {"label": "Limited", "description": "Few quality targets, mostly early-stage"}, "3": {"label": "Adequate", "description": "Multiple targets across growth stages"}, "5": {"label": "Abundant", "description": "Many high-quality targets at scale"}}', 'What is the landscape of potential investment targets in this theme? How many companies are operating at scale? What are the quality and growth profiles of leading players?'),

((SELECT id FROM public.framework_categories WHERE code = 'B'), 'Exit Environment', 'B3', 'Assessment of exit opportunities and market dynamics for realizing returns', 'To evaluate the viability and attractiveness of exit routes for portfolio companies.', 33.34, 3, '{"1": {"label": "Challenging", "description": "Limited exit options, low multiples"}, "3": {"label": "Moderate", "description": "Some strategic/financial buyers, fair multiples"}, "5": {"label": "Attractive", "description": "Multiple exit routes, high valuations"}}', 'What are the historical and current exit opportunities in this sector? Who are the likely acquirers? What multiples have been achieved in recent transactions?'),

-- Category C: Risk Profile criteria
((SELECT id FROM public.framework_categories WHERE code = 'C'), 'Technology Risk', 'C1', 'Assessment of technology maturity and adoption barriers', 'To evaluate the technological readiness and implementation risks of solutions in this theme.', 25.0, 1, '{"1": {"label": "High Risk", "description": "Unproven technology, significant technical barriers"}, "3": {"label": "Moderate Risk", "description": "Proven technology, some implementation challenges"}, "5": {"label": "Low Risk", "description": "Mature technology, established deployment"}}', 'What is the current state of technology maturity in this theme? What are the main technical barriers to adoption? How proven are the underlying technologies?'),

((SELECT id FROM public.framework_categories WHERE code = 'C'), 'Regulatory Risk', 'C2', 'Assessment of regulatory environment and policy support', 'To evaluate regulatory stability and supportiveness for the theme''s growth.', 25.0, 2, '{"1": {"label": "High Risk", "description": "Unclear/unfavorable regulations, high compliance burden"}, "3": {"label": "Moderate Risk", "description": "Evolving regulations, manageable compliance"}, "5": {"label": "Low Risk", "description": "Supportive regulations, clear compliance path"}}', 'What is the current regulatory environment for this theme? Are there supportive policies in place? What regulatory risks could impact growth?'),

((SELECT id FROM public.framework_categories WHERE code = 'C'), 'Market Risk', 'C3', 'Assessment of market demand stability and customer adoption risks', 'To evaluate the robustness of market demand and customer willingness to adopt solutions.', 25.0, 3, '{"1": {"label": "High Risk", "description": "Uncertain demand, low customer willingness to pay"}, "3": {"label": "Moderate Risk", "description": "Growing demand, some adoption barriers"}, "5": {"label": "Low Risk", "description": "Strong demand, proven customer adoption"}}', 'How stable and predictable is customer demand in this theme? What are the main barriers to customer adoption? How price-sensitive are target customers?'),

((SELECT id FROM public.framework_categories WHERE code = 'C'), 'Economic Sensitivity', 'C4', 'Assessment of theme resilience to economic cycles and external shocks', 'To evaluate how the theme performs during economic downturns and external disruptions.', 25.0, 4, '{"1": {"label": "High Sensitivity", "description": "Highly cyclical, vulnerable to economic shocks"}, "3": {"label": "Moderate Sensitivity", "description": "Some cyclical impact, manageable resilience"}, "5": {"label": "Low Sensitivity", "description": "Counter-cyclical or recession-resistant"}}', 'How does this theme typically perform during economic downturns? Is demand cyclical or defensive? What external factors could significantly impact the theme?'),

-- Category D: Impact Potential criteria
((SELECT id FROM public.framework_categories WHERE code = 'D'), 'Environmental Impact Scale', 'D1', 'Assessment of potential environmental benefits and scale of impact', 'To quantify the environmental benefits that can be achieved through this theme.', 40.0, 1, '{"1": {"label": "Limited", "description": "Minor environmental benefits, small scale"}, "3": {"label": "Moderate", "description": "Meaningful environmental impact, medium scale"}, "5": {"label": "Transformational", "description": "Major environmental benefits, large scale"}}', 'What are the quantified environmental benefits of solutions in this theme? How significant is the potential carbon reduction or environmental improvement? What is the scale of impact possible?'),

((SELECT id FROM public.framework_categories WHERE code = 'D'), 'Social Impact Potential', 'D2', 'Assessment of potential social benefits and community impact', 'To evaluate the social benefits and community impact potential of the theme.', 30.0, 2, '{"1": {"label": "Limited", "description": "Minimal social benefits"}, "3": {"label": "Moderate", "description": "Some positive social outcomes"}, "5": {"label": "Significant", "description": "Major social benefits and job creation"}}', 'What are the social benefits of this theme? Does it create jobs, improve community outcomes, or address social challenges? How measurable are these impacts?'),

((SELECT id FROM public.framework_categories WHERE code = 'D'), 'Impact Measurability', 'D3', 'Assessment of how easily impact can be measured and reported', 'To evaluate the feasibility of measuring and reporting impact outcomes.', 30.0, 3, '{"1": {"label": "Difficult", "description": "Impact hard to measure, limited metrics"}, "3": {"label": "Moderate", "description": "Some measurable metrics available"}, "5": {"label": "Easy", "description": "Clear metrics, established measurement frameworks"}}', 'How easily can the impact of this theme be measured and quantified? What metrics and frameworks are available? How standardized is impact reporting in this sector?'),

-- Category E: Fund Right to Win criteria
((SELECT id FROM public.framework_categories WHERE code = 'E'), 'Team Expertise & Network', 'E1', 'Assessment of fund team expertise and network in the theme', 'To evaluate the fund''s competitive advantages through team knowledge and connections.', 40.0, 1, '{"1": {"label": "Limited", "description": "Little team expertise or network in theme"}, "3": {"label": "Moderate", "description": "Some relevant expertise and connections"}, "5": {"label": "Strong", "description": "Deep expertise and extensive network"}}', 'What is the fund team''s experience and track record in this theme? What relevant networks and relationships exist? How strong are the connections to key players?'),

((SELECT id FROM public.framework_categories WHERE code = 'E'), 'Value Creation Capability', 'E2', 'Assessment of fund ability to add value beyond capital', 'To evaluate what unique value the fund can provide to portfolio companies in this theme.', 35.0, 2, '{"1": {"label": "Limited", "description": "Standard capital provision, limited value-add"}, "3": {"label": "Moderate", "description": "Some operational support and connections"}, "5": {"label": "Exceptional", "description": "Unique value creation through expertise/network"}}', 'What specific value can the fund add to companies in this theme beyond capital? What operational expertise, strategic guidance, or connections can be provided?'),

((SELECT id FROM public.framework_categories WHERE code = 'E'), 'Competitive Positioning', 'E3', 'Assessment of fund positioning versus other investors in the space', 'To evaluate the fund''s competitive advantages versus other investors targeting this theme.', 25.0, 3, '{"1": {"label": "Disadvantaged", "description": "Behind other investors in theme positioning"}, "3": {"label": "Competitive", "description": "Similar positioning to other investors"}, "5": {"label": "Advantaged", "description": "Clear competitive advantages over other investors"}}', 'How is the fund positioned versus other investors in this theme? What are the competitive advantages? Are there first-mover advantages or unique positioning elements?');