-- Themes 17-25: Renewable Energy Generation + Energy Transmission + Energy Storage
INSERT INTO public.taxonomy_themes (sector_id, name, description, impact, in_scope, out_of_scope, example_companies, common_edge_cases, key_identifiers) VALUES
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Renewable Energy Generation'),
  'Renewable Energy EPC & O&M',
  'Companies providing engineering, procurement, construction, installation, commissioning, operations, and maintenance services for utility-scale, commercial, and residential renewable energy projects across solar, wind, and other technologies.',
  'Enables renewable energy deployment by providing the specialized construction and operational expertise required to build and maintain reliable renewable generation assets, addressing the execution gap between project development and commercial operation.',
  ARRAY['Solar PV system design, installation, and commissioning', 'Wind turbine installation and commissioning services', 'Balance of system equipment procurement and installation', 'Renewable energy O&M and asset management services', 'Performance monitoring and optimization services', 'Module cleaning and vegetation management', 'Inverter and electrical system maintenance', 'Repowering and retrofit services for existing assets', 'Battery integration with renewable projects', 'Emergency response and repair services'],
  ARRAY['Project development and ownership without EPC/O&M services', 'Equipment manufacturing (panels, turbines) without installation', 'General electrical contracting without renewable focus', 'Grid connection infrastructure (→ Grid Infrastructure)', 'Pure software without field services'],
  ARRAY['Mortenson (EPC contractor)', 'BayWa r.e. (solar EPC/O&M)', 'Vestas (wind O&M)', 'Borrego Solar (installer)', 'Fluence (storage integration)'],
  'Developers with EPC divisions → Include if EPC offered to third parties; Manufacturers with service arms → Include service division; General contractors adding solar → Include if renewables becomes major division; Software companies → Only include if combined with field services; Integrated companies → Classify by dominant revenue stream',
  ARRAY['EPC (engineering, procurement, construction)', 'solar installation', 'wind installation', 'commissioning', 'O&M (operations and maintenance)', 'Asset management', 'performance ratio', 'availability guarantee', 'BOS (balance of system)', 'Solar PV', 'wind turbines', 'solar tracker', 'inverter', 'module cleaning', 'Repowering', 'retrofit', 'performance optimization', 'SCADA monitoring']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Renewable Energy Generation'),
  'Renewable Energy Software & Analytics',
  'Companies providing software platforms, analytics tools, and digital solutions for renewable energy asset performance monitoring, forecasting, trading, and portfolio management across solar, wind, and storage assets.',
  'Improves renewable energy economics and grid integration by optimizing generation forecasting, maximizing asset performance, and enabling sophisticated energy trading strategies that increase revenue and reliability.',
  ARRAY['Renewable energy asset performance monitoring platforms', 'Generation forecasting and weather analytics', 'Energy trading and market optimization software', 'Portfolio management and analytics platforms', 'Resource assessment and site selection tools', 'Performance benchmarking and comparative analytics', 'Predictive maintenance and diagnostics software', 'Curtailment tracking and optimization', 'Renewable energy financial modeling and valuation', 'Digital twin and simulation platforms for renewables'],
  ARRAY['Physical O&M services (→ Renewable Energy EPC & O&M)', 'Project development without software offering', 'General energy management software (→ Energy Management)', 'Equipment firmware without cloud platform', 'Investment analysis without operational focus'],
  ARRAY['Raptor Maps (solar analytics)', 'DNV (asset performance)', 'Energy Exemplar (market modeling)', 'Clir Renewables (wind analytics)', 'Solar Monkey (project management)'],
  'SCADA vendors → Include if offering analytics platform beyond basic monitoring; EPC companies with software → Include if software sold separately; Weather companies → Include if renewable energy is primary market; Trading desks → Include if providing software/analytics platform; Consultants → Include only if software platform is core offering',
  ARRAY['Asset performance monitoring', 'generation forecasting', 'energy yield assessment', 'PV monitoring', 'wind analytics', 'Resource assessment', 'solar resource', 'wind resource', 'irradiance forecasting', 'Energy trading', 'power purchase agreement (PPA)', 'merchant optimization', 'curtailment', 'Predictive maintenance', 'anomaly detection', 'underperformance analysis', 'Portfolio management', 'multi-site monitoring', 'performance benchmarking', 'Digital twin', 'simulation', 'scenario modeling']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Renewable Energy Generation'),
  'Clean Energy Advisory & Project Development',
  'Companies providing technical advisory, project development, consulting, and specialized services that enable renewable energy projects from conception through financing and commercial operation, excluding physical construction.',
  'Accelerates renewable energy deployment by providing specialized expertise in permitting, interconnection, technical due diligence, and project structuring that enables projects to navigate complex regulatory and commercial barriers.',
  ARRAY['Renewable energy project development services', 'Technical due diligence and independent engineering', 'Permitting and regulatory consulting for renewable projects', 'Environmental impact assessment and mitigation services', 'Interconnection and grid integration consulting', 'PPA structuring and negotiation advisory', 'Resource assessment and site evaluation services', 'Community solar platform development and management', 'Stakeholder engagement and community consultation', 'Renewable energy feasibility studies', 'Environmental compliance and monitoring services'],
  ARRAY['Pure project development and ownership without service offerings to others', 'General legal services without renewable specialization', 'Management consulting without energy focus', 'Financial advisory without renewable technical expertise', 'Land acquisition services', 'EPC services (→ Renewable Energy EPC & O&M)'],
  ARRAY['DNV (technical advisory)', 'Black & Veatch (engineering consulting)', 'UL (compliance and safety)', 'EnterSolar (community solar platform)', 'CSG (utility consulting)'],
  'Engineering firms with consulting arms → Include if renewable advisory is distinct service; Law firms with energy practices → Include only if providing technical/commercial advisory; Developers offering services → Include if services sold to other developers; Environmental consultants → Include if renewable energy is primary sector; Due diligence firms → Include if clean energy specialized',
  ARRAY['Project development', 'greenfield development', 'site origination', 'land acquisition', 'Independent engineer', 'technical due diligence', 'lenders engineer', 'owners engineer', 'Permitting', 'environmental permitting', 'NEPA', 'local approvals', 'zoning', 'Interconnection', 'interconnection study', 'transmission planning', 'grid impact study', 'PPA advisory', 'offtake agreement', 'power marketing', 'contract negotiation', 'Resource assessment', 'bankability study', 'P50/P90', 'energy yield', 'Community solar', 'shared solar', 'solar gardens', 'virtual net metering']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Renewable Energy Generation'),
  'Green Workforce & Skills',
  'Companies providing training, certification, workforce development, and recruitment services specifically for the renewable energy and clean technology sectors, building the skilled labor force required for energy transition.',
  'Addresses critical workforce bottlenecks limiting renewable deployment speed by training technicians, connecting workers to green jobs, and upskilling existing workforce for clean energy careers, enabling faster infrastructure buildout.',
  ARRAY['Renewable energy technician training programs', 'Solar and wind installer certification and education', 'Green jobs recruitment and marketplace platforms', 'Contractor aggregation and quality assurance networks', 'VR/AR training for renewable energy workers', 'Safety training specialized for renewables', 'Workforce development platforms for clean energy', 'Apprenticeship program management', 'Continuing education for energy professionals', 'Skills assessment and credentialing services'],
  ARRAY['General job boards without green focus', 'Traditional trade schools without renewable specialization', 'Corporate HR training platforms', 'University degree programs', 'Non-energy specific workforce development'],
  ARRAY['Solar Energy International (training)', 'HeatSpring (online education)', 'Contractor Connection (network management)', 'Skillcat (trades training)', 'IREC (certification standards)'],
  'Trade schools adding solar courses → Include if renewable energy becomes major program; Job boards with green categories → Include only if green jobs are primary focus; Equipment manufacturers with training → Include if training offered commercially; Industry associations → Include only if providing commercial training services; General upskilling platforms → Include if clean energy specialized',
  ARRAY['Renewable energy training', 'solar training', 'wind technician training', 'Green jobs', 'clean energy careers', 'renewable energy workforce', 'Certification programs', 'NABCEP', 'skills training', 'technical training', 'Workforce development', 'apprenticeships', 'on-the-job training', 'Contractor networks', 'installer networks', 'technician marketplaces', 'VR training', 'AR training', 'simulation-based learning', 'Continuing education', 'recertification', 'safety training']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Energy Transmission'),
  'Grid Infrastructure & Connection',
  'Companies manufacturing equipment and providing engineering, construction, installation, and integration services for electrical transmission and distribution infrastructure that connects renewable energy generation to the grid and modernizes electrical networks.',
  'Enables renewable energy integration by building and upgrading the physical electrical infrastructure required to transmit clean power from generation sites to consumption points, addressing grid capacity constraints that limit renewable deployment.',
  ARRAY['Transmission and distribution equipment manufacturing (transformers, switchgear, cables, protection systems)', 'Grid connection EPC services for renewable projects', 'Substation design, construction, and upgrade services', 'Transmission and distribution line installation', 'Interconnection engineering and project management', 'Grid protection equipment installation and commissioning', 'Underground cable installation services', 'Grid reinforcement and capacity upgrade services', 'Testing and commissioning of grid infrastructure', 'Greenfield and brownfield electrical infrastructure development'],
  ARRAY['Utility ownership and operations', 'General electrical contracting without grid focus', 'Telecommunications infrastructure', 'Renewable energy generation equipment installation (→ Renewable Energy EPC)'],
  ARRAY['Quanta Services (transmission infrastructure)', 'MYR Group (electrical construction)', 'ABB (equipment + services)', 'Siemens Energy (grid solutions)', 'Balfour Beatty (power transmission)'],
  'Electrical contractors → Include only if specialized in transmission/distribution; Utilities with construction divisions → Include if services offered to third parties; Equipment manufacturers with installation → Include entire company, classify by primary revenue; Renewable EPC firms doing grid work → Classify by dominant revenue source; Smart grid hardware installers → Classify in Smart Grid if digital systems included',
  ARRAY['Grid connection', 'interconnection', 'transmission infrastructure', 'distribution infrastructure', 'Substation construction', 'substation upgrades', 'switchgear installation', 'Transmission lines', 'distribution lines', 'underground cabling', 'overhead lines', 'Grid integration', 'renewable integration', 'grid reinforcement', 'Interconnection queue', 'grid connection services', 'point of interconnection (POI)', 'High voltage engineering', 'medium voltage', 'grid protection systems']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Energy Transmission'),
  'Smart Grid & Demand Response',
  'Companies providing digital platforms, software systems, and analytics that enable grid flexibility, distributed energy resource management, demand response programs, and intelligent grid operations for utilities and system operators to accommodate variable renewable generation.',
  'Enables higher renewable penetration by using digital technology to balance supply and demand dynamically, manage distributed resources, and maintain grid stability with variable generation, overcoming the intermittency challenge of renewables.',
  ARRAY['Demand response aggregation platforms serving utilities and system operators', 'Distributed energy resource management systems (DERMS) for grid operators', 'Grid analytics and optimization software for utilities', 'Distribution management systems (DMS)', 'Advanced metering infrastructure software platforms', 'Microgrid control and management systems', 'Grid flexibility marketplaces for wholesale/utility markets', 'Power flow modeling and simulation tools', 'Outage management and restoration systems', 'Grid edge intelligence and optimization platforms for utilities'],
  ARRAY['Smart meter hardware manufacturing', 'Traditional SCADA systems without smart grid capabilities', 'Utility billing and customer information systems', 'C&I customer energy apps (→ Energy Management & Optimization)', 'Building-level demand response (→ Building Control & Optimization)'],
  ARRAY['Grid4C (grid analytics)', 'AutoGrid (DERMS/VPP for utilities)', 'Smarter Grid Solutions (active network management)', 'Opus One Solutions (grid planning)', 'Itron (AMI software)'],
  'AMI vendors with software → Include software platform, exclude meter hardware; VPP operators → Include here if serving utilities; in Energy Management if serving C&I; Building platforms offering DR → Classify in Buildings if building-focused; Utilities with software platforms → Include if offered to other utilities/ISOs; EV charging platforms with V2G → Classify in EV Charging if charging-focused',
  ARRAY['Smart grid', 'intelligent grid', 'grid modernization', 'distribution management system (DMS)', 'Demand response', 'demand flexibility', 'load management', 'demand-side management', 'DERMS (distributed energy resource management system)', 'VPP (virtual power plant)', 'Advanced metering infrastructure (AMI)', 'smart meters', 'meter data management', 'Grid analytics', 'grid optimization', 'power flow analysis', 'distribution optimization', 'Microgrid', 'microgrid control', 'islanding', 'grid edge', 'grid flexibility marketplace']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Energy Transmission'),
  'Grid Operations & Maintenance',
  'Companies providing specialized operations, maintenance, inspection, and asset management services for electrical transmission and distribution infrastructure to ensure reliable and efficient grid performance.',
  'Maintains grid reliability and capacity for renewable integration by preventing outages, optimizing asset performance, and extending infrastructure lifespan through proactive maintenance, reducing grid constraints on clean energy deployment.',
  ARRAY['Vegetation management services for transmission corridors', 'Drone and aerial inspection services for grid infrastructure', 'Predictive maintenance and condition monitoring platforms', 'Grid asset management software and services', 'Storm response and emergency restoration services', 'Thermographic and diagnostic inspection services', 'Pole inspection and maintenance services', 'Underground cable fault detection and location', 'Asset lifecycle management and replacement planning', 'Grid resilience assessment and hardening services'],
  ARRAY['Electrical equipment manufacturing', 'Utility operations and control centers', 'General landscaping without grid specialization', 'Construction of new infrastructure (→ Grid Infrastructure & Connection)', 'Grid planning and engineering (→ Clean Energy Advisory)'],
  ARRAY['Asplundh Tree Expert (vegetation management)', 'Osmose Utilities Services (inspection)', 'Sharper Shape (drone inspection)', 'PrecisionHawk (aerial intelligence)', 'Woolpert (geospatial services)'],
  'General tree services → Include only if transmission/distribution is primary market; Drone companies → Include if grid inspection is specialized offering; Software companies → Include if grid-specific asset management focus; Utilities with maintenance arms → Include if services offered to other utilities; Emergency services → Include only if grid infrastructure specialized',
  ARRAY['Vegetation management', 'right-of-way maintenance', 'tree trimming', 'line clearance', 'Grid inspection', 'transmission inspection', 'drone inspection', 'aerial inspection', 'Predictive maintenance', 'condition monitoring', 'asset health monitoring', 'Storm response', 'emergency restoration', 'outage restoration', 'Asset management', 'grid asset management', 'lifecycle management', 'Infrared inspection', 'thermography', 'LiDAR scanning', 'satellite monitoring']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Energy Storage'),
  'Storage Integration & O&M',
  'Companies that manufacture battery systems, design, install, integrate, commission, operate, and maintain battery energy storage systems across utility-scale, commercial, industrial, and residential applications, enabling storage deployment and long-term performance.',
  'Accelerates energy storage adoption by providing the manufacturing, engineering, installation, and operational expertise required to deploy reliable battery systems that enable renewable energy firming, grid services, and resilience, making variable renewables dispatchable.',
  ARRAY['Battery systems and component manufacturing (cells, modules, packs, inverters, thermal management)', 'Raw material processing for batteries (lithium refining, cathode production, anode materials)', 'Battery storage system design and engineering services', 'Storage installation and commissioning services', 'Hybrid renewable + storage integration services', 'Storage O&M and performance management services', 'Safety system installation and monitoring', 'Residential storage installation networks', 'Storage-as-a-Service providers', 'Repowering and retrofit services for storage assets', 'Battery augmentation and capacity expansion services', 'Grid-forming and grid-following inverter integration'],
  ARRAY['Lithium/cobalt/nickel mining (extractive operations)', 'Project development and ownership without operational services', 'Utilities owning storage assets without service offerings', 'Battery recycling and second-life (→ Battery Lifecycle)'],
  ARRAY['Tesla Energy (manufacturing + services)', 'Fluence (systems integration)', 'Powin Energy (integration)', 'Convergent Energy + Power (storage services)', 'Soltage (storage-as-a-service)'],
  'Solar installers adding storage → Include if storage becomes significant offering; Storage manufacturers with services → Include entire company, classify by primary revenue; Developers with EPC teams → Include if services sold to third parties; Companies spanning integration and software → Classify here if physical installation/O&M dominates; Virtual power plants using storage → Classify in Energy Management if VPP software focus',
  ARRAY['BESS (battery energy storage system)', 'energy storage installation', 'battery installation', 'Storage EPC', 'storage integration', 'hybrid systems', 'solar-plus-storage', 'Storage commissioning', 'testing and commissioning', 'energization', 'Storage O&M', 'battery maintenance', 'performance monitoring', 'Storage-as-a-Service (STaaS)', 'energy storage service agreements', 'Residential storage', 'C&I storage', 'utility-scale storage', 'behind-the-meter storage', 'Fire safety', 'battery safety systems', 'thermal management']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Energy Storage'),
  'Storage Software & Analytics',
  'Companies providing software platforms, analytics tools, and optimization systems that maximize the operational and financial performance of battery energy storage assets through intelligent dispatch, trading, and performance management.',
  'Increases storage deployment economics by optimizing revenue streams, extending asset life through intelligent operation, and enabling participation in multiple value streams simultaneously, improving the business case for storage investments.',
  ARRAY['Battery management system software (cloud-based platforms)', 'Storage dispatch optimization and trading platforms', 'Revenue stacking and value optimization software', 'Battery analytics and diagnostic platforms', 'Performance monitoring and warranty management tools', 'Storage aggregation and VPP platforms (software only)', 'Market participation and bidding platforms', 'Predictive maintenance software for storage systems', 'Energy arbitrage and price forecasting tools', 'Multi-site storage portfolio management software'],
  ARRAY['Embedded firmware for BMS hardware (unless cloud platform offered)', 'Physical energy trading operations', 'Project finance and investment platforms', 'General energy management software (→ Energy Management & Optimization)', 'Hardware manufacturing and installation (→ Storage Integration & O&M)'],
  ARRAY['Habitat Energy (trading optimization)', 'Energy Toolbase (storage modeling)', 'Geli (software platform)', 'Everest Energy (storage operating system)', 'Stem (AI-driven optimization software)'],
  'BMS companies → Include software platforms, exclude hardware-embedded firmware only; VPP platforms with storage → Include if storage is primary asset class, software-only offering; Energy management platforms adding storage → Classify by primary customer segment and offering; Analytics companies → Include if battery storage is specialized focus; Companies with both software and integration → Classify here only if software revenue dominates',
  ARRAY['Battery management system (BMS software)', 'battery analytics', 'storage optimization', 'Storage dispatch', 'energy arbitrage', 'revenue stacking', 'ancillary services optimization', 'Storage trading', 'market participation', 'frequency regulation', 'capacity markets', 'Battery diagnostics', 'state of health (SOH)', 'state of charge (SOC)', 'degradation monitoring', 'Warranty management', 'performance guarantees', 'predictive analytics', 'Virtual power plant (VPP storage)', 'fleet management', 'aggregation platforms']
);