-- Populate the new taxonomy structure (v2.0)
-- This migration adds the complete taxonomy hierarchy: pillars, sectors, themes, business models, and their relationships

-- =====================================================
-- STEP 1: Insert Pillars
-- =====================================================
INSERT INTO taxonomy_pillars (name, description, display_order) VALUES
('Decarbonisation', 'Reducing greenhouse gas emissions across transport, mobility, and industrial sectors', 1),
('Buildings', 'Energy efficiency, electrification, and sustainable construction in built environments', 2),
('Industry', 'Industrial energy efficiency, electrification, and emissions management', 3),
('Agriculture', 'Precision farming, regenerative practices, and sustainable food production', 4),
('Energy Transition', 'Renewable energy deployment, grid modernization, and clean energy services', 5),
('Resource Sustainability', 'Water management, circular economy, land conservation, and pollution reduction', 6)
ON CONFLICT DO NOTHING;

-- =====================================================
-- STEP 2: Insert Sectors (linked to pillars)
-- =====================================================
DO $$
DECLARE
  pillar_decarb_id uuid;
  pillar_buildings_id uuid;
  pillar_industry_id uuid;
  pillar_agriculture_id uuid;
  pillar_energy_id uuid;
  pillar_resource_id uuid;
BEGIN
  -- Get pillar IDs
  SELECT id INTO pillar_decarb_id FROM taxonomy_pillars WHERE name = 'Decarbonisation';
  SELECT id INTO pillar_buildings_id FROM taxonomy_pillars WHERE name = 'Buildings';
  SELECT id INTO pillar_industry_id FROM taxonomy_pillars WHERE name = 'Industry';
  SELECT id INTO pillar_agriculture_id FROM taxonomy_pillars WHERE name = 'Agriculture';
  SELECT id INTO pillar_energy_id FROM taxonomy_pillars WHERE name = 'Energy Transition';
  SELECT id INTO pillar_resource_id FROM taxonomy_pillars WHERE name = 'Resource Sustainability';

  -- Insert sectors
  INSERT INTO taxonomy_sectors (pillar_id, name, description, display_order) VALUES
  (pillar_decarb_id, 'Mobility', 'Transport electrification, alternative fuels, and logistics optimization', 1),
  (pillar_buildings_id, 'Buildings', 'Building efficiency, retrofits, and sustainable construction', 1),
  (pillar_industry_id, 'Industry', 'Industrial processes, electrification, and emissions management', 1),
  (pillar_agriculture_id, 'Agriculture', 'Precision agriculture and regenerative farming practices', 1),
  (pillar_energy_id, 'Clean Energy Services', 'Renewable energy deployment and workforce development', 1),
  (pillar_energy_id, 'Energy Transmission', 'Grid infrastructure, smart grid, and operations', 2),
  (pillar_energy_id, 'Energy Storage', 'Battery storage integration and software optimization', 3),
  (pillar_resource_id, 'Water Management', 'Water treatment, efficiency, and smart infrastructure', 1),
  (pillar_resource_id, 'Circular Economy', 'Recycling, reuse, and sustainable materials', 2),
  (pillar_resource_id, 'Land & Conservation', 'Ecosystem services, restoration, and sustainable land management', 3),
  (pillar_resource_id, 'Pollution Reduction', 'Air quality monitoring and soil remediation', 4)
  ON CONFLICT DO NOTHING;
END $$;

-- =====================================================
-- STEP 3: Insert Business Models
-- =====================================================
INSERT INTO taxonomy_business_models (name, description) VALUES
('Network operators', 'Operating infrastructure networks at scale'),
('Hardware manufacturers', 'Manufacturing physical equipment and systems'),
('Software platforms', 'Digital platforms and software solutions'),
('Installation services', 'Physical installation and commissioning services'),
('Infrastructure owners', 'Ownership and operation of physical assets'),
('Managed charging providers', 'Managed services for charging infrastructure'),
('Fleet planning software', 'Fleet management and optimization software'),
('FaaS providers', 'Fleet-as-a-Service business models'),
('Fleet solutions integrators', 'Integrated fleet electrification solutions'),
('EV fleet management platforms', 'Digital platforms for EV fleet management'),
('Hydrogen infrastructure providers', 'Hydrogen production and distribution infrastructure'),
('Renewable diesel producers', 'Production of renewable diesel fuels'),
('E-fuel manufacturers', 'Manufacturing synthetic and e-fuels'),
('Electrolyzer manufacturers/operators', 'Electrolyzer production and operation'),
('Fuel cell companies', 'Fuel cell technology development and manufacturing'),
('Micromobility operators', 'Operating shared micromobility services'),
('Demand-responsive transit platforms', 'On-demand transit technology platforms'),
('Journey planning apps', 'Multi-modal journey planning applications'),
('Transit operations software', 'Software for transit operations and optimization'),
('Car-sharing platforms', 'Car-sharing and ride-pooling platforms'),
('Digital freight forwarders', 'Digital freight forwarding services'),
('Freight marketplaces', 'Digital marketplaces for freight matching'),
('Last-mile platforms', 'Last-mile delivery optimization platforms'),
('Delivery orchestration', 'Delivery coordination and orchestration platforms'),
('Parcel locker operators', 'Operating parcel locker networks'),
('Battery recyclers', 'Battery collection and recycling operations'),
('Second-life deployment', 'Second-life battery deployment and management'),
('Materials recovery', 'Material recovery from batteries'),
('Collection/logistics', 'Battery collection and reverse logistics'),
('Battery diagnostics', 'Battery testing and diagnostic services'),
('Maritime AI platforms', 'AI-powered maritime optimization platforms'),
('Vessel performance software', 'Vessel performance monitoring software'),
('Rotor sail manufacturers', 'Manufacturing wind-assisted propulsion systems'),
('Air lubrication systems', 'Air lubrication technology for vessels'),
('Voyage optimization', 'Maritime voyage optimization services'),
('Contrail prediction platforms', 'Contrail prediction and avoidance technology'),
('Flight planning software', 'Flight planning and optimization software'),
('Fuel efficiency analytics', 'Aviation fuel efficiency analytics platforms'),
('Airport operations optimization', 'Airport ground operations optimization'),
('Aviation data platforms', 'Aviation data and analytics platforms'),
('BMS/BAS providers', 'Building management system providers'),
('HVAC optimization platforms', 'HVAC control and optimization platforms'),
('Smart thermostat platforms', 'Smart thermostat and climate control platforms'),
('Building intelligence', 'Intelligent building analytics and control'),
('Energy analytics with control', 'Energy analytics with automated control capabilities'),
('Retrofit contractor networks', 'Networks of building retrofit contractors'),
('Retrofit financing', 'Financing platforms for building retrofits'),
('Geothermal installation', 'Geothermal heating system installation'),
('Building upgrades', 'Comprehensive building upgrade services'),
('Air sealing services', 'Air sealing and weatherization services'),
('Solar + storage installers', 'Combined solar and storage installation'),
('Residential VPP platforms', 'Virtual power plant platforms for homes'),
('Home energy monitoring', 'Home energy monitoring and management'),
('Home electrification', 'Comprehensive home electrification services'),
('Community solar', 'Community solar platform development'),
('Low-carbon concrete producers', 'Manufacturing low-carbon concrete products'),
('Mass timber manufacturers', 'Manufacturing mass timber and CLT products'),
('Bio-based materials', 'Production of bio-based construction materials'),
('Reclaimed material platforms', 'Marketplaces for reclaimed building materials'),
('Embodied carbon tools', 'Software for embodied carbon calculation'),
('Motor efficiency providers', 'Industrial motor efficiency solutions'),
('Industrial efficiency consultants', 'Industrial energy efficiency consulting'),
('Energy analytics platforms', 'Industrial energy analytics platforms'),
('C&I demand response', 'Commercial and industrial demand response'),
('Energy performance contractors', 'Energy performance contracting services'),
('Electric boiler providers', 'Industrial electric boiler systems'),
('Thermal battery companies', 'Thermal energy storage solutions'),
('Heat pump system integrators', 'Industrial heat pump system integration'),
('Process electrification consultants', 'Industrial process electrification consulting'),
('Emissions monitoring systems', 'Continuous emissions monitoring systems'),
('Methane detection services', 'Methane leak detection and mitigation'),
('Carbon accounting platforms', 'Industrial carbon accounting software'),
('Emissions control equipment', 'Emissions control equipment and services'),
('LDAR services', 'Leak detection and repair services'),
('Farm data platforms', 'Agricultural data management platforms'),
('Precision agronomy services', 'Precision agriculture consulting and services'),
('Crop intelligence', 'Crop monitoring and intelligence platforms'),
('Agricultural robotics', 'Agricultural automation and robotics'),
('Crop monitoring', 'Satellite and drone-based crop monitoring'),
('Carbon credit platforms', 'Agricultural carbon credit platforms'),
('Biological nitrogen providers', 'Biological nitrogen fixation solutions'),
('Transition financing', 'Financing for agricultural transitions'),
('Soil carbon measurement', 'Soil carbon measurement and verification'),
('Grazing management', 'Regenerative grazing management services'),
('Renewable EPC contractors', 'Renewable energy EPC contractors'),
('Manufacturing + services', 'Equipment manufacturing with service offerings'),
('O&M providers', 'Operations and maintenance service providers'),
('Repowering services', 'Renewable asset repowering services'),
('Inspection/maintenance', 'Inspection and maintenance services'),
('Renewable marketplaces', 'Renewable energy procurement marketplaces'),
('PPA analytics platforms', 'PPA management and analytics platforms'),
('REC trading', 'Renewable energy certificate trading'),
('VPPA advisory', 'Virtual PPA structuring and advisory'),
('Procurement platforms', 'Corporate renewable procurement platforms'),
('Technical advisory', 'Renewable energy technical advisory'),
('Permitting consultants', 'Renewable permitting and regulatory consulting'),
('Independent engineers', 'Independent engineering services'),
('Community solar platforms', 'Community solar development platforms'),
('PPA structuring', 'PPA structuring and negotiation'),
('Training programs', 'Renewable energy training programs'),
('Online education', 'Online renewable energy education platforms'),
('Contractor networks', 'Renewable contractor networks'),
('Trades training platforms', 'Trade skills training platforms'),
('Certification bodies', 'Renewable energy certification services'),
('Transmission infrastructure EPC', 'Transmission infrastructure EPC'),
('Equipment + services', 'Equipment manufacturing with services'),
('Grid connection services', 'Grid interconnection services'),
('Substation construction', 'Substation construction and upgrades'),
('Line installation', 'Transmission line installation'),
('DERMS/VPP for utilities', 'DERMS and VPP platforms for utilities'),
('Grid analytics', 'Grid analytics and optimization software'),
('DMS platforms', 'Distribution management systems'),
('AMI software', 'Advanced metering infrastructure software'),
('Microgrid control', 'Microgrid control and management systems'),
('Vegetation management', 'Transmission corridor vegetation management'),
('Drone inspection', 'Drone-based grid infrastructure inspection'),
('Predictive maintenance platforms', 'Predictive maintenance for grid assets'),
('Asset management software', 'Grid asset management software'),
('Storm response', 'Emergency grid restoration services'),
('Battery system manufacturers', 'Battery energy storage system manufacturers'),
('Storage integration EPC', 'Energy storage EPC services'),
('O&M providers', 'Storage operations and maintenance'),
('Storage-as-a-Service', 'Storage-as-a-Service business models'),
('Installation networks', 'Storage installation service networks'),
('Trading optimization software', 'Energy storage trading optimization'),
('Storage modeling platforms', 'Storage performance modeling platforms'),
('BMS software platforms', 'Battery management system software'),
('Operating systems', 'Storage operating system platforms'),
('AI-driven optimization', 'AI-powered storage optimization'),
('Industrial water treatment', 'Industrial wastewater treatment'),
('Membrane technology', 'Membrane treatment technology'),
('Water recycling systems', 'Water reuse and recycling systems'),
('Modular treatment', 'Modular water treatment solutions'),
('ZLD providers', 'Zero liquid discharge system providers'),
('Leak detection systems', 'Water leak detection systems'),
('Pressure management', 'Water pressure management systems'),
('Smart water solutions', 'Comprehensive smart water solutions'),
('Digital water platforms', 'Digital water management platforms'),
('Analytics platforms', 'Water analytics platforms'),
('Smart irrigation', 'Smart irrigation systems and services'),
('Customer engagement platforms', 'Water customer engagement platforms'),
('Leak repair services', 'Water leak repair services'),
('Landscape intelligence', 'Landscape water intelligence platforms'),
('Efficiency consulting', 'Water efficiency consulting'),
('E-waste processors', 'Electronic waste processing'),
('AI sorting technology', 'AI-powered recycling sorting'),
('Hard-to-recycle specialists', 'Specialized difficult material recycling'),
('Textile recovery', 'Textile recycling and recovery'),
('MRF operators', 'Material recovery facility operators'),
('Returns optimization', 'Returns optimization platforms'),
('Recommerce marketplaces', 'Secondary goods marketplaces'),
('IT asset management', 'IT asset disposition and refurbishment'),
('Device buyback', 'Device buyback and trade-in platforms'),
('Surplus exchange', 'Industrial surplus exchange platforms'),
('Equipment sharing platforms', 'B2B equipment sharing platforms'),
('PaaS enablement', 'Product-as-a-Service enablement'),
('Peer-to-peer rental', 'P2P rental and sharing platforms'),
('Surplus marketplaces', 'Material surplus marketplaces'),
('Circular design consulting', 'Circular design consulting services'),
('Seaweed packaging', 'Seaweed-based packaging materials'),
('Mycelium materials', 'Mycelium-based materials'),
('Fiber-based packaging', 'Sustainable fiber-based packaging'),
('Reusable packaging systems', 'Reusable packaging system operations'),
('Food preservation tech', 'Food preservation technology'),
('Industrial remanufacturing', 'Industrial remanufacturing services'),
('Furniture upcycling', 'Furniture upcycling and remanufacturing'),
('Industrial symbiosis networks', 'Industrial symbiosis facilitation'),
('Textile upcycling', 'Textile upcycling operations'),
('Certified remanufactured parts', 'Certified remanufactured component sales'),
('Carbon standard bodies', 'Carbon standard setting and registry'),
('Carbon marketplaces', 'Carbon credit trading marketplaces'),
('Ecological asset platforms', 'Natural capital and biodiversity platforms'),
('Biodiversity monitoring', 'Biodiversity monitoring and verification'),
('Natural capital advisory', 'Natural capital accounting and advisory'),
('Reforestation services', 'Reforestation and afforestation services'),
('Forest restoration platforms', 'Forest restoration platforms'),
('Aerial reforestation', 'Aerial reforestation technology'),
('Restoration contractors', 'Ecological restoration contractors'),
('Ecological restoration', 'Comprehensive ecological restoration'),
('Forest carbon monitoring', 'Forest carbon monitoring platforms'),
('Forest carbon marketplaces', 'Forest carbon credit marketplaces'),
('Forest management software', 'Sustainable forest management software'),
('Ecosystem mapping', 'Ecosystem mapping and monitoring'),
('Restoration platforms', 'Restoration project platforms'),
('Air quality monitoring platforms', 'Air quality monitoring networks'),
('Air quality solutions', 'Air quality improvement solutions'),
('Air quality data APIs', 'Air quality data platforms and APIs'),
('Indoor air quality services', 'Indoor air quality services'),
('Air quality forecasting', 'Air pollution forecasting'),
('Bioremediation services', 'Bioremediation service providers'),
('Soil remediation contractors', 'Soil remediation contractors'),
('In-situ treatment technology', 'In-situ soil treatment technology'),
('Contaminated materials management', 'Contaminated materials management'),
('Remediation services', 'Comprehensive remediation services')
ON CONFLICT DO NOTHING;

-- (Continued in next part due to length...)