-- Themes 4-10: Remaining Mobility + Buildings
INSERT INTO public.taxonomy_themes (sector_id, name, description, impact, in_scope, out_of_scope, example_companies, common_edge_cases, key_identifiers) VALUES
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Mobility'),
  'Public & Shared Transport',
  'Companies that develop technology, operate services, or provide infrastructure enabling public transit, shared mobility, and multi-modal transportation to reduce private vehicle use and improve sustainable urban mobility access.',
  'Reduces transport emissions by shifting trips from private vehicles to shared modes, increasing vehicle utilization rates, and optimizing transit operations to make sustainable transport more accessible and efficient than individual car ownership.',
  ARRAY['Shared micromobility services (bikes, e-bikes, scooters, mopeds)', 'Car-sharing and ride-pooling platforms', 'Multi-modal journey planning and MaaS platforms', 'Transit operations software and optimization systems', 'Transit ticketing and fare payment systems', 'Demand-responsive and paratransit services', 'Transit data analytics and passenger flow management', 'First/last-mile connectivity solutions', 'Public transit technology and management systems'],
  ARRAY['Transit operators and authorities (TfL, RATP, MTA, etc.)', 'Private ride-hailing without shared/pooling focus', 'Vehicle manufacturing for transit systems', 'Transit infrastructure construction (rails, stations)', 'Traditional taxi services without technology platform', 'Freight and goods delivery (→ Logistics Decarbonisation)'],
  ARRAY['Via (demand-responsive transit)', 'Lime (micromobility)', 'Transit (app)', 'Optibus (transit operations platform)', 'Zipcar (car-sharing)'],
  'Ride-hailing companies with pooling → Include only if pooled/shared rides >50% of trips; Navigation apps with transit features → Include if public/shared transport is primary focus; Parking apps promoting transit → Classify based on primary revenue source; Mobility data/analytics companies → Include if primarily serving shared/public mobility; E-scooter manufacturers vs operators → Classify operators here, manufacturers elsewhere',
  ARRAY['MaaS', 'micromobility', 'DRT (demand-responsive transport)', 'paratransit', 'ride-pooling', 'car-sharing', 'transit optimization']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Mobility'),
  'Logistics Decarbonisation',
  'Companies that optimize freight movement and last-mile delivery through technology platforms, route optimization, and sustainable logistics solutions to reduce emissions from goods transportation.',
  'Reduces freight emissions by optimizing routes, improving vehicle utilization, enabling modal shifts, and coordinating deliveries to eliminate empty miles and inefficient distribution patterns in the movement of goods.',
  ARRAY['Route optimization software for freight and delivery', 'Digital freight marketplaces and load matching platforms', 'Last-mile delivery optimization and management platforms', 'Supply chain emissions tracking and reporting tools', 'Urban consolidation and microhub operations', 'Parcel locker networks and alternative delivery points', 'Logistics orchestration and multi-carrier platforms', 'Reverse logistics optimization for returns', 'Freight pooling and collaborative logistics platforms'],
  ARRAY['Logistics companies without technology platform (traditional 3PLs)', 'Vehicle manufacturing for logistics', 'Warehouse automation without transport focus', 'Pure e-commerce platforms without logistics focus', 'Fleet electrification services (→ Fleet Electrification)'],
  ARRAY['Flexport (digital freight forwarder)', 'Convoy (freight marketplace)', 'Stuart (last-mile platform)', 'Bringg (delivery orchestration)', 'InstaBox (parcel lockers)'],
  'E-commerce companies with logistics arms → Include only if logistics offered to third parties; Traditional logistics companies adding digital → Include if platform is primary value; Fleet management for logistics → Classify in Fleet Electrification if EV focus; Warehouse robotics companies → Only include if optimizing transport not storage; Food delivery platforms → Include only if expanding to broader logistics',
  ARRAY['TMS (transport management system)', 'last-mile', 'middle-mile', 'load matching', 'digital freight', 'microhubs', 'PUDO']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Mobility'),
  'Battery Lifecycle',
  'Companies managing the complete lifecycle of batteries from manufacturing with recycled materials through second-life applications, collection, recycling, and material recovery, maximizing value and minimizing environmental impact of battery systems.',
  'Reduces environmental impact of electrification by extending battery useful life through second-life applications, recovering critical materials for new production, and preventing hazardous waste from entering landfills.',
  ARRAY['Battery cell and module manufacturing using recycled materials', 'Battery collection and reverse logistics services', 'Battery recycling facilities and operations', 'Second-life battery deployment and integration', 'Battery diagnostic and testing services', 'Battery materials recovery and processing', 'Battery asset management platforms', 'Battery-as-a-Service offerings across applications', 'Battery refurbishment and remanufacturing', 'Battery passport and traceability solutions'],
  ARRAY['New battery cell manufacturing from virgin materials (→ Storage Integration & O&M)', 'Mining of virgin materials for batteries', 'Electric vehicle manufacturing', 'Stationary storage deployment without lifecycle focus (→ Storage Integration)', 'Battery management systems for new batteries only'],
  ARRAY['Redwood Materials (recycling)', 'Li-Cycle (materials recovery)', 'Aceleron (second-life)', 'Circu Li-ion (collection/logistics)', 'Battery Resourcers (recycling)'],
  'Battery manufacturers with recycling → Include if recycling is separate business unit; EV manufacturers with battery programs → Include if offered as service to others; Energy storage companies using second-life → Classify by primary business model; Chemical companies recovering materials → Include if batteries are primary feedstock; Diagnostics for new vs. used batteries → Include if lifecycle management focus',
  ARRAY['Battery recycling', 'battery collection', 'battery logistics', 'battery lifecycle', 'Second-life batteries', 'battery repurposing', 'stationary storage from EV batteries', 'Black mass', 'battery materials recovery', 'lithium recovery', 'cobalt recovery', 'Battery diagnostics', 'battery health', 'state of health (SOH)', 'battery testing', 'Battery-as-a-Service (BaaS)', 'battery leasing', 'battery swapping', 'Urban mining', 'critical minerals recovery', 'hydrometallurgy', 'pyrometallurgy']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Mobility'),
  'Marine & Aviation Decarbonisation',
  'Companies developing technologies, manufacturing efficiency equipment, and providing operational solutions to reduce emissions from shipping and aviation through efficiency improvements, alternative propulsion, and optimized operations.',
  'Addresses emissions from hard-to-abate transport sectors by enabling fuel switching, operational efficiency, and new propulsion technologies in international shipping and aviation where electrification faces fundamental constraints.',
  ARRAY['Marine and aviation efficiency technology manufacturing (rotor sails, winglets, hull coatings, propulsion efficiency systems)', 'Voyage and route optimization software for shipping', 'Flight planning and optimization systems', 'Port call and berth optimization platforms', 'Vessel and aircraft performance monitoring systems', 'Emissions monitoring and reporting for maritime/aviation', 'Green port technology and shore power systems', 'Wind-assisted propulsion and efficiency technologies', 'Aircraft efficiency technologies and modifications', 'Maritime and aviation operational efficiency services'],
  ARRAY['Shipbuilding and aircraft manufacturing', 'Traditional port operations without sustainability focus', 'Airline and shipping line operators', 'Airport and port infrastructure construction', 'General freight forwarding without optimization', 'SAF and alternative marine fuel production (→ Alternative Fuels)'],
  ARRAY['Windward (voyage optimization)', 'NAPA (vessel performance)', 'ZeroAvia (hydrogen aviation)', 'Norsepower (rotor sails)', 'METIS (maritime AI optimization)'],
  'Fuel producers for marine/aviation → Classify in Alternative Fuels if producing SAF/marine fuels; Port operators with optimization → Include if offering software/services to others; Shipping companies with tech platforms → Include if platform offered externally; Weather routing services → Include if emissions reduction is primary value prop; Cargo booking platforms → Only include if optimization is core offering',
  ARRAY['Maritime decarbonisation', 'green shipping', 'sustainable shipping', 'ship efficiency', 'Sustainable aviation', 'flight optimization', 'aviation emissions', 'contrail reduction', 'Voyage optimization', 'vessel performance', 'slow steaming', 'just-in-time arrival', 'Sustainable aviation fuel (SAF)', 'marine biofuels', 'green ammonia shipping', 'Port optimization', 'port call optimization', 'berth planning', 'green ports', 'Flight planning', 'air traffic optimization', 'continuous descent operations']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Buildings'),
  'Building Control & Optimization',
  'Companies providing intelligent building management systems, energy optimization software, and automated control solutions that actively reduce energy consumption and emissions in commercial and residential buildings.',
  'Reduces building emissions through real-time optimization of HVAC, lighting, and other systems based on occupancy, weather, and grid conditions, typically achieving 20-40% energy savings without capital upgrades.',
  ARRAY['Building management and automation systems', 'HVAC control and optimization platforms', 'Energy monitoring and analytics software with control capabilities', 'Smart thermostat platforms and intelligent climate control', 'Occupancy-based control and space optimization systems', 'Demand response aggregation for buildings', 'Continuous commissioning and fault detection services', 'Building performance optimization services', 'Integrated workplace management systems with energy focus'],
  ARRAY['Passive monitoring without active control capabilities', 'Manual energy audits without ongoing optimization', 'HVAC equipment manufacturing (→ Building Retrofits)', 'Building materials or insulation (→ Building Retrofits)', 'Pure compliance reporting without optimization'],
  ARRAY['BrainBox AI (HVAC optimization)', 'Aquicore (building performance)', 'GridPoint (energy management)', '75F (building intelligence)', 'Verdigris (energy analytics)'],
  'IoT platforms with building focus → Include if energy optimization is primary value; Property management software → Include only if active energy management included; Smart home platforms → Classify in Residential Decarbonisation if consumer-focused; Utility demand response programs → Only include third-party aggregators; Digital twin platforms → Include if used for energy optimization not just visualization',
  ARRAY['Building management system (BMS)', 'building automation system (BAS)', 'energy management system', 'HVAC optimization', 'smart thermostats', 'intelligent controls', 'demand-controlled ventilation', 'Occupancy sensors', 'occupancy analytics', 'space utilization', 'presence detection', 'Demand response', 'load flexibility', 'grid-interactive buildings', 'virtual power plant', 'Energy monitoring', 'submetering', 'real-time energy data', 'performance analytics', 'Fault detection and diagnostics (FDD)', 'predictive maintenance', 'commissioning']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Buildings'),
  'Building Retrofits',
  'Companies manufacturing efficient equipment and providing physical building envelope improvements, insulation upgrades, and efficiency installations that reduce energy demand through passive and active measures in existing building stock.',
  'Reduces building energy consumption by improving thermal performance, air tightness, and equipment efficiency, addressing the massive emissions from existing buildings that cannot be solved through controls alone.',
  ARRAY['Heat pump and efficient HVAC equipment manufacturing', 'Insulation installation and weatherization services', 'Window and door replacement services', 'Air sealing and building envelope contractors', 'Whole-building retrofit coordination and project management', 'Retrofit assessment and energy audit services', 'Digital platforms connecting homeowners with retrofit contractors', 'Financing platforms for retrofit projects', 'Heat pump installation when part of broader retrofit', 'Ventilation system upgrades and heat recovery'],
  ARRAY['Building materials manufacturing (insulation, windows) without installation services', 'New construction services', 'General construction without efficiency focus', 'Standalone HVAC replacement without envelope work', 'Smart controls without physical improvements (→ Building Control & Optimization)'],
  ARRAY['RetrofitWorks (contractor network)', 'Sealed (retrofit financing)', 'Dandelion Energy (geothermal retrofits)', 'BlocPower (building upgrades)', 'Aerobarrier (air sealing)'],
  'HVAC installers offering insulation → Include if comprehensive retrofit approach; General contractors adding efficiency → Include if specialized retrofit division; Energy service companies (ESCOs) → Include if focused on physical improvements; Materials distributors → Only include if providing installation services; Home renovation platforms → Include only if energy efficiency is primary focus',
  ARRAY['Building retrofit', 'deep retrofit', 'energy retrofit', 'thermal upgrade', 'building envelope', 'Insulation', 'weatherization', 'air sealing', 'draught proofing', 'thermal bridge', 'Window replacement', 'glazing upgrade', 'external wall insulation', 'cavity wall insulation', 'Heat recovery ventilation', 'mechanical ventilation with heat recovery (MVHR)', 'Retrofit assessment', 'energy audit', 'thermal imaging', 'blower door test', 'One-stop-shop retrofit', 'whole-house retrofit', 'EnerPHit', 'Passivhaus']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Buildings'),
  'Residential Decarbonisation',
  'Companies providing integrated platforms, technologies, and services that enable comprehensive home energy transitions including electrification, renewable energy, and smart home energy management for residential customers.',
  'Accelerates residential decarbonisation by simplifying the complex journey from fossil fuel dependence to all-electric homes powered by renewable energy, addressing market barriers of complexity, upfront cost, and contractor coordination.',
  ARRAY['Residential solar and battery installation services', 'Heat pump sales and installation for homes', 'Integrated home energy platforms combining multiple technologies', 'Home energy assessment and planning services', 'Residential virtual power plant operators', 'Smart home energy management systems', 'Home electrification consulting and project management', 'Residential energy-as-a-service offerings', 'Community solar platforms serving residential customers'],
  ARRAY['Equipment manufacturing - solar panels (→ Renewable Energy EPC), heat pumps (→ Building Retrofits), batteries (→ Storage Integration)', 'Commercial building services', 'Utility companies without specific residential programs', 'General HVAC contractors without decarbonisation focus', 'Home automation without energy focus'],
  ARRAY['Sunrun (solar + storage)', 'OhmConnect (residential VPP)', 'Sense (home energy monitoring)', 'Elephant Energy (home electrification)', 'Arcadia (community solar)'],
  'Solar installers adding batteries → Include as integrated offering expands; HVAC companies installing heat pumps → Include if part of electrification strategy; Smart home companies → Include only if energy management is core value prop; Energy retailers with home services → Include if offering installation/management; Property tech platforms → Include only if residential energy transition is primary',
  ARRAY['Home electrification', 'residential solar', 'home battery storage', 'home energy management', 'Heat pump installation', 'residential heat pumps', 'air source heat pump', 'ground source heat pump', 'Solar-plus-storage', 'residential VPP', 'home virtual power plant', 'distributed energy resources', 'Smart home energy', 'connected home', 'home energy monitoring', 'energy disaggregation', 'Home energy assessment', 'home energy score', 'home energy report', 'Residential demand response', 'time-of-use optimization', 'energy arbitrage']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Buildings'),
  'Sustainable Construction Materials',
  'Companies producing, distributing, or enabling the use of low-carbon and circular construction materials including bio-based materials, recycled content, and carbon-negative products that reduce the embodied carbon of buildings.',
  'Reduces construction emissions by replacing carbon-intensive materials (concrete, steel) with low-carbon alternatives, utilizing waste streams, and sequestering carbon in building materials, addressing the 11% of global emissions from building materials.',
  ARRAY['Low-carbon concrete and cement production', 'Mass timber and engineered wood manufacturing', 'Bio-based building material production', 'Recycled and reclaimed material processing and distribution', 'Material marketplace platforms for sustainable materials', 'Embodied carbon calculation and optimization tools', 'Construction waste recycling and recovery services', 'Modular and prefabricated low-carbon building systems', 'Carbon-storing material technologies'],
  ARRAY['Traditional building material production without sustainability focus', 'General construction companies using materials', 'Forestry operations and logging without processing', 'Mining and raw material extraction (limestone quarrying, ore extraction)', 'Architectural design services'],
  ARRAY['CarbonCure (low-carbon concrete)', 'Boston Metal (green steel)', 'Biomason (bio-concrete)', 'The ReUse Network (reclaimed materials)', 'EC3 (embodied carbon calculator)'],
  'Concrete companies with low-carbon products → Include if separate product line; Timber companies entering mass timber → Include if CLT/engineered wood focus; Waste companies processing C&D waste → Include if producing building materials; Chemical companies with bio-based products → Include if building materials focus; Software for material selection → Include if sustainability is primary value',
  ARRAY['Low-carbon concrete', 'green concrete', 'carbon-negative concrete', 'geopolymer concrete', 'Mass timber', 'cross-laminated timber (CLT)', 'engineered wood', 'sustainable timber', 'Bio-based materials', 'mycelium materials', 'hempcrete', 'bamboo construction', 'Recycled materials', 'reclaimed materials', 'circular construction', 'urban mining', 'Embodied carbon', 'life cycle assessment (LCA)', 'environmental product declaration (EPD)', 'Material passports', 'material banks', 'construction waste recycling']
);