-- Themes 26-39: Resource Sustainability (Water + Waste + Land + Pollution + Climate Tech)
INSERT INTO public.taxonomy_themes (sector_id, name, description, impact, in_scope, out_of_scope, example_companies, common_edge_cases, key_identifiers) VALUES
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Water Management'),
  'Water Treatment & Reuse',
  'Companies manufacturing treatment equipment and providing technologies, systems, and services that treat wastewater, enable water reuse and recycling, and deliver clean water solutions across industrial, municipal, and commercial applications.',
  'Reduces freshwater consumption and pollution by treating wastewater for reuse, enabling circular water use in industry and municipalities, and providing decentralized treatment solutions that reduce strain on centralized water infrastructure.',
  ARRAY['Wastewater treatment system design and installation', 'Water recycling and reuse technology', 'Industrial water treatment solutions', 'Decentralized treatment systems', 'Membrane and filtration technology', 'Biological treatment systems', 'Advanced oxidation processes', 'Zero liquid discharge systems', 'Greywater and blackwater treatment', 'Water treatment chemicals and solutions', 'Treatment system operations and maintenance'],
  ARRAY['Water infrastructure construction (pipes, pumping stations)', 'Water utility operations', 'Drinking water treatment for primary distribution', 'Desalination without reuse component', 'Water testing labs without treatment services'],
  ARRAY['Xylem (treatment equipment)', 'Evoqua (water solutions)', 'Epic Cleantec (building water reuse)', 'Cambrian Innovation (industrial treatment)', 'Source (atmospheric water)'],
  'Equipment manufacturers → Include if providing complete systems not just components; Engineering firms → Include if water treatment specialized; Chemical companies → Include if treatment focus, not just chemical supply; Utilities → Include third-party service providers only; Consulting firms → Include only if treatment systems are core service',
  ARRAY['Wastewater treatment', 'water reuse', 'water recycling', 'reclaimed water', 'Membrane bioreactor (MBR)', 'reverse osmosis', 'ultrafiltration', 'nanofiltration', 'Industrial water treatment', 'process water', 'cooling water', 'zero liquid discharge', 'Greywater', 'blackwater', 'on-site treatment', 'decentralized wastewater', 'Biological treatment', 'aerobic', 'anaerobic', 'activated sludge']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Water Management'),
  'Water Efficiency & Management',
  'Companies providing smart water technologies, leak detection, monitoring systems, and water management platforms that optimize water use, reduce losses, and improve efficiency across agriculture, industry, and municipalities.',
  'Reduces water consumption and infrastructure strain through intelligent monitoring, leak detection, and optimization systems that prevent water loss and enable precise water application in agriculture and industry.',
  ARRAY['Smart water metering and analytics platforms', 'Leak detection and water loss prevention systems', 'Irrigation optimization and precision watering', 'Water usage monitoring and reporting software', 'Pressure management and hydraulic optimization', 'Smart irrigation controllers and systems', 'Water quality monitoring sensors and platforms', 'Water balance and accounting software', 'Agricultural water management platforms', 'Industrial water efficiency consulting'],
  ARRAY['Water treatment technology (→ Water Treatment & Reuse)', 'Traditional plumbing services', 'Irrigation hardware without smart technology', 'General IoT platforms without water focus', 'Water rights and trading platforms'],
  ARRAY['WaterSmart (customer engagement)', 'Banyan Water (efficiency platform)', 'Dropcountr (analytics)', 'CropX (soil sensing)', 'Utilis (satellite leak detection)'],
  'Smart meter manufacturers → Include software/analytics platform, hardware alone insufficient; Irrigation companies → Include if smart/precision irrigation is core offering; Agriculture platforms → Include if water management is primary focus; Software companies → Include if water-specific not general purpose; Utilities → Include third-party technology providers only',
  ARRAY['Smart water metering', 'AMI water', 'water analytics', 'customer engagement', 'Leak detection', 'water loss', 'non-revenue water', 'acoustic monitoring', 'Irrigation management', 'ET-based irrigation', 'soil moisture sensing', 'precision irrigation', 'Water monitoring', 'SCADA water', 'pressure monitoring', 'flow monitoring', 'Water efficiency', 'conservation', 'demand management', 'water audits']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Recycling & Material Recovery',
  'Companies providing collection, sorting, processing, and recovery services for recyclable materials, transforming waste streams into valuable secondary raw materials for remanufacturing.',
  'Reduces resource extraction and landfill waste by recovering valuable materials from waste streams and returning them to productive use, displacing virgin material production and creating circular material flows.',
  ARRAY['Municipal recycling collection and MRF operations', 'Commercial and industrial recycling services', 'Single-stream and multi-stream recycling processing', 'Material recovery and commodity sales', 'Specialized recycling (e-waste, textiles, plastics, metals)', 'Recycling technology and sorting equipment', 'Contamination reduction and quality improvement', 'Recycling data and traceability platforms', 'Collection route optimization for recycling', 'Material brokerage and trading platforms'],
  ARRAY['Waste-to-energy operations', 'Landfill operations', 'Composting services (→ Waste Treatment if composting focus)', 'Upcycling to higher value (→ Upcycling & Remanufacturing)', 'Product take-back without recycling (→ Reverse Logistics)'],
  ARRAY['Recology (recycling services)', 'AMP Robotics (AI sorting)', 'Rubicon (waste/recycling platform)', 'TerraCycle (specialty recycling)', 'Closed Loop Partners (recycling infrastructure)'],
  'Waste companies adding recycling → Include if recycling is significant service line; Technology providers → Include if recycling-specific automation/AI; E-waste companies → Include if recovery/recycling focus; Reuse programs → Classify in appropriate circular economy theme; Chemical recycling → Include if producing recycled materials',
  ARRAY['Material recovery facility (MRF)', 'single-stream recycling', 'comingled recycling', 'Optical sorting', 'AI sorting', 'robotic sorting', 'NIR sensors', 'E-waste recycling', 'WEEE', 'electronics recycling', 'IT asset disposition', 'Textile recycling', 'garment recycling', 'fiber recovery', 'Plastics recycling', 'mechanical recycling', 'chemical recycling', 'plastic recovery']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Waste Treatment & Diversion',
  'Companies providing waste collection, treatment, and diversion services including composting, anaerobic digestion, and waste-to-energy solutions that prevent landfilling and recover value from organic and residual waste.',
  'Diverts waste from landfills while recovering energy or nutrients through composting, anaerobic digestion, and thermal treatment, reducing methane emissions and creating circular flows of organic matter and energy.',
  ARRAY['Commercial and industrial waste collection services', 'Organic waste composting operations and services', 'Anaerobic digestion facilities and biogas production', 'Waste-to-energy facility operations', 'Food waste collection and processing', 'Construction and demolition waste processing', 'Hazardous waste treatment services', 'Waste diversion consulting and program management', 'Waste tracking and reporting platforms', 'Zero waste program implementation'],
  ARRAY['Landfill operations without diversion', 'General hauling without waste focus', 'Recycling services (→ Recycling & Material Recovery)', 'Product refurbishment (→ Reverse Logistics)', 'Biogas upgrading to fuel (→ Alternative Fuels if fuel production focus)'],
  ARRAY['Waste Management Inc (diversified)', 'Rubicon (tech-enabled waste)', 'Harvest Power (organics)', 'Covanta (waste-to-energy)', 'Recology (composting)'],
  'Traditional waste companies → Include if waste diversion/treatment is meaningful offering; Haulers → Include if diversion programs are core service; Biogas facilities → Include if waste treatment focused; Food waste → Include collection and processing, not source reduction only; Zero waste consultants → Include if implementing waste systems',
  ARRAY['Waste collection', 'commercial waste', 'municipal solid waste', 'waste hauling', 'Composting', 'organic waste', 'food waste composting', 'yard waste', 'Anaerobic digestion', 'AD', 'biogas', 'renewable natural gas', 'digestate', 'Waste-to-energy', 'WtE', 'incineration', 'thermal treatment', 'energy recovery', 'Zero waste', 'waste diversion', 'landfill diversion', 'waste reduction']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Reverse Logistics & Refurbishment',
  'Companies managing product take-back, returns, refurbishment, and redistribution systems that enable products to be repaired, resold, or remarketed rather than discarded, extending product lifespans through reverse supply chains.',
  'Extends product lifecycles by creating efficient reverse logistics systems for returns, repairs, and refurbishment, keeping products in use longer and reducing demand for new manufacturing.',
  ARRAY['Take-back and reverse logistics program management', 'Refurbishment and remanufacturing services', 'IT asset disposition and refurbishment services', 'Returns optimization software and platforms', 'Trade-in and buyback platform operators', 'Repair network coordination and management', 'Asset recovery and redistribution services', 'Circular supply chain software and tracking platforms', 'Product authenticity and condition assessment services', 'Recommerce marketplace platforms'],
  ARRAY['Traditional forward logistics without circularity focus', 'New product manufacturing', 'Warranty services only without reuse focus', 'Pure retail returns (without refurbishment/reuse)', 'Financial leasing without product recovery'],
  ARRAY['Optoro (returns optimization)', 'B-Stock (recommerce marketplace)', 'Blancco (IT asset management)', 'Renew (device buyback)', 'Rheaply (surplus exchange)'],
  'Logistics companies with reverse flows → Include if circular focus is primary; Manufacturers with refurbishment → Include if offered as separate service; Warranty companies → Include only if repair/reuse is core model; Marketplaces → Include if secondary/refurbished is primary inventory; Device buyback → Include here; repair services alone might also fit',
  ARRAY['Reverse logistics', 'product take-back', 'product returns', 'reverse supply chain', 'Refurbishment', 'remanufacturing', 'certified refurbished', 'factory refurbished', 'IT asset disposition', 'ITAD', 'e-waste refurbishment', 'device refurbishment', 'Returns management', 'returns optimization', 'reverse supply chain software', 'Buyback programs', 'trade-in platforms', 'product residual value', 'Circular economy software', 'material passports', 'product traceability']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Sharing & Reuse Models',
  'Companies providing digital platforms, services, and infrastructure that enable sharing economy models, rental systems, product-as-a-service, and asset utilization optimization, maximizing the use of existing products and reducing demand for new production.',
  'Reduces resource consumption and manufacturing emissions by maximizing utilization of existing products through sharing, rental, and subscription models, displacing demand for new production and extending effective product lifespans through access-based consumption.',
  ARRAY['B2B equipment and tool sharing platforms', 'Product-as-a-Service platform enablement software', 'Peer-to-peer rental and sharing marketplaces', 'Circular design software and consulting', 'Asset utilization optimization platforms', 'Subscription and rental management software', 'Material exchange and surplus marketplaces', 'Sharing infrastructure services (storage, logistics, cleaning)', 'PaaS transition consulting and implementation services', 'Circular business model advisory'],
  ARRAY['Product manufacturing - even if sold via PaaS (classify by product type in relevant theme)', 'Software-as-a-Service without physical product component', 'Traditional financial leasing without product stewardship', 'Pure consumer rental (cars, apartments) without sustainability/circularity focus', 'Reusable product manufacturing (→ Sustainable Materials & Packaging)'],
  ARRAY['Grover (electronics subscription platform)', 'Rheaply (surplus marketplace)', 'Floow2 (equipment sharing)', 'Stuffstr (product lifecycle platform)', 'Sabas (PaaS enablement)'],
  'Consumer rental platforms → Include only if circularity/sustainability is core value prop and measurable impact; SaaS companies → Exclude unless enabling physical product sharing/PaaS; Manufacturers offering PaaS → Classify in relevant product theme, not here; Marketplaces → Include if enabling reuse/sharing vs. facilitating new purchases; Infrastructure providers → Include if supporting sharing economy, exclude traditional logistics',
  ARRAY['Sharing economy', 'collaborative consumption', 'access over ownership', 'Product-as-a-Service (PaaS)', 'equipment-as-a-service', 'subscription models', 'Rental platforms', 'peer-to-peer sharing', 'B2B equipment sharing', 'Tool libraries', 'equipment sharing', 'asset sharing', 'circular design', 'Usage-based models', 'pay-per-use', 'performance-based contracts', 'Asset utilization', 'idle capacity', 'sharing infrastructure']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Sustainable Materials & Packaging',
  'Companies manufacturing and distributing sustainable material alternatives including bio-based materials, compostable products, reusable packaging systems, and low-impact materials that replace conventional petroleum-based and resource-intensive materials across applications.',
  'Reduces fossil fuel consumption, plastic pollution, and resource extraction by replacing conventional materials with renewable, biodegradable, reusable, or lower-impact alternatives derived from sustainable sources.',
  ARRAY['Sustainable packaging material manufacturing (compostable, bio-based, recycled content)', 'Reusable packaging system manufacturing and operations', 'Bio-based and compostable material production', 'Sustainable materials distribution and supply platforms', 'Packaging optimization software and consulting services', 'Material traceability and certification platforms', 'Alternative material commercialization and production', 'Sustainable materials marketplaces', 'Packaging design services for sustainability', 'Material innovation and substitution services'],
  ARRAY['Virgin plastic production without bio-based/recycled content', 'Traditional packaging companies without sustainability focus', 'Paper mills and conventional material production', 'Agricultural feedstock production without material processing', 'Material recycling operations (→ Recycling & Material Recovery)', 'Platforms enabling product sharing (→ Sharing & Reuse Models)'],
  ARRAY['Notpla (seaweed packaging)', 'Ecovative (mycelium materials)', 'Footprint (fiber-based packaging)', 'Loop (reusable packaging systems)', 'Apeel (food coating technology)'],
  'Packaging companies adding sustainable lines → Include if sustainability is significant business; Material manufacturers → Include bio-based and novel materials, exclude conventional; Recycled content packaging → Include if packaging production is primary business; Food preservation tech → Include if reducing packaging needs or extending shelf life; Agricultural waste processors → Include if producing materials, exclude if just waste management; Reusable vs sharing platforms → Reusable containers = here; platforms enabling sharing = Theme 31',
  ARRAY['Sustainable packaging', 'eco-friendly packaging', 'compostable packaging', 'biodegradable materials', 'Reusable packaging', 'returnable containers', 'durable packaging systems', 'Bio-based materials', 'bioplastics', 'bio-polymers', 'plant-based materials', 'Packaging optimization', 'lightweighting', 'source reduction', 'minimal packaging', 'Material traceability', 'material passports', 'supply chain transparency', 'Certified materials', 'FSC', 'Cradle to Cradle', 'compostability certification', 'Alternative fibers', 'mycelium', 'seaweed', 'agricultural waste materials']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Waste & Circular Economy'),
  'Upcycling & Remanufacturing',
  'Companies transforming waste materials and used products into higher-value goods through creative reuse, remanufacturing, and upcycling processes that create value from materials otherwise destined for disposal.',
  'Diverts waste from landfills while creating economic value by transforming discarded materials and products into new goods of equal or higher quality, displacing virgin production and creating circular value chains.',
  ARRAY['Industrial remanufacturing services and facilities', 'Component harvesting and resale operations', 'Upcycled product manufacturing and brands', 'Waste-to-product transformation platforms', 'Industrial symbiosis facilitation and networks', 'Remanufacturing certification and standards', 'Material upcycling technology and processes', 'By-product valorization services', 'Remanufacturing equipment and tooling'],
  ARRAY['Basic mechanical recycling (→ Recycling & Material Recovery)', 'Downcycling operations (lower value outputs)', 'Artisan/craft businesses without scale', 'Energy recovery from waste (waste-to-energy)', 'Simple sorting without transformation'],
  ARRAY['Caterpillar Remanufacturing (industrial)', 'Rype Office (furniture upcycling)', 'Kalundborg Symbiosis (industrial ecology)', 'Hilos (textile upcycling)', 'RTS (certified remanufactured parts)'],
  'Recycling companies → Include here if output is higher value than input, in Recycling if same/lower; Refurbishment services → Classify in Reverse Logistics if focus is returns/resale; Manufacturing with recycled content → Include if transforming waste into premium products; Industrial waste processors → Include if creating valuable by-products, exclude if just disposal; Creative reuse brands → Include if scaled production, exclude if artisanal/craft only',
  ARRAY['Upcycling', 'creative reuse', 'waste-to-product', 'value-added recycling', 'Remanufacturing', 'factory rebuilds', 'component harvesting', 'certified remanufactured', 'Industrial symbiosis', 'by-product synergy', 'waste exchange', 'Waste valorization', 'residual value', 'material transformation', 'Design for remanufacturing', 'modular design', 'standardized components', 'Cascading use', 'material hierarchy', 'downcycling prevention']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Land & Conservation'),
  'Natural Capital & Ecosystem Services',
  'Companies developing markets, platforms, and verification services that monetize ecosystem services including carbon sequestration, biodiversity credits, water quality, and other nature-based solutions, creating financial incentives for conservation and restoration.',
  'Accelerates conservation and restoration by creating revenue streams from ecosystem services, enabling landowners and communities to be compensated for environmental stewardship and making nature protection economically competitive with extractive land uses.',
  ARRAY['Carbon credit development and project management', 'Biodiversity credit platforms and marketplaces', 'Natural capital accounting software and services', 'Ecosystem services verification and certification', 'Carbon and biodiversity credit trading platforms', 'Impact measurement and MRV technology', 'Conservation finance structuring and advisory', 'Registry and standard-setting services', 'Remote sensing and monitoring for nature credits', 'Payment for ecosystem services program management'],
  ARRAY['Land acquisition and ownership without credit development', 'Traditional conservation NGOs without market mechanisms', 'Government conservation programs', 'Academic research without commercialization', 'Carbon capture technology (industrial, not nature-based)'],
  ARRAY['Verra (carbon standard)', 'Patch (carbon marketplace)', 'Regen Network (ecological assets)', 'NatureMetrics (biodiversity monitoring)', 'Silvestrum (natural capital advisory)'],
  'Agricultural carbon credits → Include here if credits are primary business; in Regenerative Farming if farming services dominate; Forest owners selling credits → Include if credit development is active business, not passive landholding; Technology providers → Include if specifically for nature-based credit markets; Brokers vs. developers → Include both if focused on ecosystem service markets; Compliance vs. voluntary markets → Include both',
  ARRAY['Carbon credits', 'carbon offsets', 'voluntary carbon markets', 'compliance carbon markets', 'Biodiversity credits', 'biodiversity net gain', 'species credits', 'habitat banking', 'Natural capital accounting', 'ecosystem services valuation', 'payment for ecosystem services (PES)', 'Nature-based solutions', 'blue carbon', 'forest carbon', 'soil carbon credits', 'Conservation finance', 'impact verification', 'additionality', 'permanence', 'MRV (monitoring, reporting, verification)', 'remote sensing', 'carbon registries']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Land & Conservation'),
  'Ecosystem Restoration',
  'Companies providing active restoration services including reforestation, wetland restoration, coastal rehabilitation, and habitat reconstruction that physically restore degraded ecosystems to functional ecological states.',
  'Reverses ecosystem degradation by actively rebuilding natural habitats, restoring ecological functions, sequestering carbon, improving water quality, and enhancing biodiversity in areas damaged by human activity or natural disasters.',
  ARRAY['Reforestation and afforestation services', 'Wetland and peatland restoration contractors', 'Coastal and marine habitat restoration services', 'Mine site and industrial rehabilitation services', 'Urban greening and ecological infrastructure services', 'Native plant nurseries for restoration (not ornamental)', 'Ecological engineering and design services', 'Restoration monitoring and adaptive management', 'Seed collection and native species propagation', 'Restoration project management and consulting'],
  ARRAY['Landscaping for aesthetics without ecological function', 'Traditional forestry and timber operations', 'Agricultural services (→ Agriculture themes)', 'Land development and construction', 'Ornamental horticulture and gardening'],
  ARRAY['Land Life Company (reforestation)', 'Terraformation (forest restoration)', 'DroneSeed (aerial reforestation)', 'Mast Reforestation (restoration services)', 'Biohabitats (ecological restoration)'],
  'Forestry companies with restoration → Include if restoration is distinct service line; Landscape architects → Include only if ecological restoration is primary focus; Nurseries → Include if native species for restoration, exclude ornamental; Drone companies → Include if restoration is primary application; Urban tree planting → Include if ecological function emphasized, exclude if purely aesthetic',
  ARRAY['Reforestation', 'afforestation', 'forest restoration', 'tree planting', 'Wetland restoration', 'peatland restoration', 'mangrove restoration', 'coastal restoration', 'Habitat restoration', 'ecological restoration', 'rewilding', 'species reintroduction', 'Mine site rehabilitation', 'brownfield restoration', 'reclamation', 'Urban greening', 'green infrastructure', 'bioswales', 'urban forests', 'Native species', 'ecological engineering', 'assisted regeneration']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Land & Conservation'),
  'Sustainable Land Management',
  'Companies providing technology platforms, monitoring systems, and advisory services for sustainable forestry, land use optimization, and landscape-level conservation planning that balance economic use with ecological preservation.',
  'Enables sustainable land use by providing data, analytics, and decision support for forest management, land use planning, and landscape conservation, preventing deforestation and degradation while maintaining productive use.',
  ARRAY['Forest inventory and monitoring platforms', 'Precision forestry software and analytics', 'Sustainable harvest planning and optimization', 'Fire risk assessment and management systems', 'Land use planning and decision support tools', 'Deforestation monitoring and alert systems', 'Forest certification and compliance services', 'Timber traceability and supply chain platforms', 'Forest carbon accounting and reporting', 'Landscape-level conservation planning tools'],
  ARRAY['Timber harvesting operations and logging', 'Pulp and paper production', 'Agricultural machinery and services (→ Agriculture themes)', 'Real estate development', 'Fire suppression equipment manufacturing'],
  ARRAY['Pachama (forest carbon monitoring)', 'NCX (forest carbon marketplace)', 'Silvacom (forest management software)', 'Dendra Systems (ecosystem mapping)', 'Restor (restoration platform)'],
  'Forestry companies with software → Include software division if offered commercially; Carbon credit developers → Classify in Natural Capital if credits are primary; Agricultural land use → Classify in Agriculture if farming is focus; Fire detection technology → Include if wildfire/forest management focused; Timber companies → Include only monitoring/planning tools, not operations',
  ARRAY['Sustainable forestry', 'forest management', 'timber certification', 'FSC', 'PEFC', 'Forest inventory', 'forest monitoring', 'forest carbon accounting', 'Precision forestry', 'forest analytics', 'harvest planning', 'yield optimization', 'Fire risk management', 'wildfire prevention', 'fire detection', 'Land use planning', 'landscape management', 'spatial planning', 'Deforestation monitoring', 'forest change detection', 'REDD+']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Pollution Reduction'),
  'Air Quality Monitoring & Control',
  'Companies providing monitoring systems, analytics platforms, and mitigation services for ambient and indoor air quality that measure, forecast, and reduce air pollution exposure in communities and buildings (excluding industrial point-source emissions).',
  'Reduces health impacts from air pollution by enabling real-time monitoring, pollution forecasting, exposure reduction, and air purification in populated areas, addressing the public health crisis of ambient air pollution.',
  ARRAY['Ambient air quality monitoring networks and sensors', 'Indoor air quality monitoring and analytics platforms', 'Low-cost air quality sensor deployment', 'Air quality forecasting and predictive analytics', 'Community air monitoring programs and platforms', 'Air purification and filtration systems', 'Pollution exposure assessment and mapping', 'Clean air zone technology and enforcement', 'Environmental justice air quality initiatives', 'Air quality data platforms and APIs'],
  ARRAY['Industrial emissions monitoring (→ Industrial Emissions Management)', 'HVAC systems without air quality focus', 'Weather forecasting without pollution focus', 'Academic research without commercial product', 'Government monitoring networks'],
  ARRAY['IQAir (air quality platform)', 'Clarity Movement (sensors)', 'Plume Labs (personal exposure)', 'Molekule (air purification)', 'BreezoMeter (air quality API)'],
  'Sensor manufacturers → Include if providing platform/network, not just hardware; HVAC companies → Include only if air quality is primary value proposition; Weather services → Include if air quality is major offering; Academic spinouts → Include if commercial product/service; Consumer devices → Include if connected platform with public health data',
  ARRAY['Air quality monitoring', 'ambient air quality', 'AQI (air quality index)', 'PM2.5', 'PM10', 'Indoor air quality (IAQ)', 'building air quality', 'workplace air quality', 'Air quality sensors', 'monitoring networks', 'low-cost sensors', 'reference monitors', 'Air pollution forecasting', 'air quality analytics', 'exposure assessment', 'Air purification', 'filtration', 'clean air zones', 'pollution mitigation', 'Community air monitoring', 'hyperlocal air quality', 'environmental justice']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Pollution Reduction'),
  'Soil & Water Remediation',
  'Companies providing assessment, treatment, and cleanup services for contaminated soil and water across industrial, agricultural, and urban sites, removing pollutants and restoring environmental quality.',
  'Removes legacy pollution from soil and water resources through physical, chemical, and biological treatment methods, enabling safe land reuse, protecting water resources, and reversing historical environmental damage.',
  ARRAY['Soil remediation and brownfield cleanup services', 'Groundwater treatment and pump-and-treat systems', 'In-situ and ex-situ treatment technologies', 'Contamination assessment and site investigation', 'Bioremediation and phytoremediation services', 'Soil vapor extraction and air sparging', 'Chemical oxidation and reduction treatments', 'Sediment remediation and dredging', 'Landfill capping and containment', 'Environmental liability management'],
  ARRAY['Regulatory compliance consulting only', 'Environmental insurance without remediation', 'General construction without remediation focus', 'Water treatment for consumption (→ Water Treatment)', 'Waste disposal services (→ Waste Treatment)'],
  ARRAY['AECOM (remediation services)', 'Arcadis (environmental consulting)', 'Cascade Environmental (soil remediation)', 'Regenesis (bioremediation)', 'Clean Harbors (environmental services)'],
  'Engineering firms → Include if remediation is primary service line; Environmental consultants → Include if active cleanup not just assessment; Construction companies → Include only if remediation specialized; Chemical companies → Include if remediation products/services focus; General contractors → Include only with remediation division',
  ARRAY['Soil remediation', 'brownfield cleanup', 'contaminated land', 'soil treatment', 'Groundwater remediation', 'aquifer treatment', 'pump and treat', 'groundwater extraction', 'Bioremediation', 'microbial degradation', 'phytoremediation', 'natural attenuation', 'In-situ treatment', 'soil vapor extraction', 'air sparging', 'chemical oxidation', 'Ex-situ treatment', 'soil washing', 'thermal desorption', 'excavation and treatment', 'Environmental liability', 'site cleanup', 'environmental insurance', 'closure costs']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Climate Technology'),
  'Climate Technology & Innovation',
  'Companies developing frontier climate technologies including carbon capture and storage, direct air capture, ocean-based carbon removal, and other innovative approaches to climate mitigation that don''t fit traditional categories.',
  'Addresses hard-to-abate emissions and enables carbon removal at scale through breakthrough technologies including carbon capture, direct air capture, enhanced weathering, and ocean-based solutions that are critical for achieving net-zero.',
  ARRAY['Direct air capture technology and facilities', 'Point-source carbon capture systems', 'Carbon storage and sequestration services', 'Enhanced weathering and mineral carbonation', 'Ocean-based carbon removal technologies', 'Biochar production and deployment', 'Climate tech R&D and commercialization', 'Carbon removal verification and certification', 'Negative emissions technology', 'Novel climate mitigation approaches'],
  ARRAY['Nature-based carbon credits (→ Natural Capital)', 'Conventional renewable energy (→ relevant energy themes)', 'Industrial efficiency without capture (→ Industrial themes)', 'Conventional agricultural practices', 'Climate risk analytics alone'],
  ARRAY['Climeworks (direct air capture)', 'Carbon Engineering (DAC)', 'CarbonCure (concrete mineralization)', 'Charm Industrial (carbon removal)', 'Running Tide (ocean carbon removal)'],
  'Industrial companies adding CCUS → Include if carbon capture is distinct business unit; Technology developers → Include if climate application is primary; Research institutions → Include only if commercializing technology; Service providers → Include if enabling novel climate tech deployment; Verification companies → Include if focused on frontier carbon removal',
  ARRAY['Direct air capture (DAC)', 'carbon dioxide removal (CDR)', 'negative emissions', 'Carbon capture and storage (CCS)', 'CCUS', 'point-source capture', 'post-combustion', 'Enhanced weathering', 'mineral carbonation', 'alkalinity enhancement', 'Ocean carbon removal', 'marine CDR', 'ocean alkalinity', 'blue carbon tech', 'Biochar', 'pyrolysis', 'carbon sequestration', 'soil carbon storage', 'Carbon removal credits', 'durable CDR', 'permanent storage', 'frontier carbon']
);