-- Themes 12-20: Industry + Agriculture + Renewable Energy Generation
INSERT INTO public.taxonomy_themes (sector_id, name, description, impact, in_scope, out_of_scope, example_companies, common_edge_cases, key_identifiers) VALUES
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Industry'),
  'Industrial Energy Efficiency & Optimisation',
  'Companies providing technologies, software, and services that reduce industrial energy consumption through process optimization, waste heat recovery, equipment efficiency improvements, and energy management systems across manufacturing and industrial facilities.',
  'Reduces industrial emissions by optimizing energy use in manufacturing processes, recovering wasted energy, and improving equipment efficiency, addressing the significant energy intensity of industrial operations that account for ~24% of global emissions.',
  ARRAY['Industrial energy management software and platforms', 'Process optimization and control systems for energy reduction', 'Waste heat recovery system design and installation', 'Compressed air system optimization services', 'Motor and drive efficiency upgrades and retrofits', 'Industrial energy auditing and consulting services', 'Energy monitoring and submetering systems', 'AI-driven process optimization for energy reduction', 'Industrial demand response and load management'],
  ARRAY['Equipment manufacturing without service component', 'Basic industrial automation without energy focus', 'General industrial IoT without efficiency focus', 'Electrification projects (→ Industrial Electrification & Heat)', 'Emissions monitoring without energy optimization (→ Industrial Emissions Management)'],
  ARRAY['Turntide Technologies (motor efficiency)', 'Cascade Energy (industrial efficiency)', 'Enverus (energy analytics)', 'Akselos (digital twin optimization)', 'ENGIE Insight (energy management)'],
  'Automation companies with efficiency modules → Include if energy is primary value prop; Industrial IoT platforms → Include only if energy optimization is core use case; Equipment manufacturers with service arms → Include if services are offered separately; Utilities with industrial programs → Include third-party service providers only; Consulting firms → Include only specialized industrial energy practices',
  ARRAY['Industrial energy management', 'energy efficiency', 'process optimization', 'energy intensity', 'Waste heat recovery', 'heat exchanger', 'combined heat and power (CHP)', 'cogeneration', 'Compressed air optimization', 'motor efficiency', 'variable frequency drives (VFD)', 'Energy monitoring', 'industrial IoT', 'predictive analytics', 'digital twin', 'Energy audit', 'ISO 50001', 'energy performance contracting', 'measurement and verification', 'Steam optimization', 'boiler efficiency', 'thermal efficiency', 'pinch analysis']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Industry'),
  'Industrial Electrification & Heat',
  'Companies manufacturing electrification equipment and enabling the transition from fossil fuel-based industrial heating to electric alternatives including heat pumps, electric boilers, and other electrification technologies for industrial processes.',
  'Eliminates direct industrial emissions by replacing natural gas, coal, and oil-fired heating with electric systems powered by increasingly clean grids, addressing hard-to-abate industrial heat that represents ~10% of global emissions.',
  ARRAY['Industrial heat pump system design and installation', 'Electric boiler and furnace installation services', 'Process electrification consulting and engineering', 'High-temperature heat pump development and deployment', 'Thermal energy storage systems for industrial use', 'Electric heating system integration and controls', 'Feasibility studies for industrial electrification', 'Hybrid heating systems combining electric and other sources', 'Industrial flexibility services for electrified processes'],
  ARRAY['Heat pump manufacturing without installation services (manufacturing alone would go in this theme)', 'Residential or commercial heat pumps (→ Building themes)', 'General electrical contracting without specialization', 'Energy efficiency without fuel switching (→ Industrial Energy Efficiency)', 'Hydrogen for heating (→ Alternative Fuels)'],
  ARRAY['AtmosZero (electric boilers)', 'Rondo Energy (thermal batteries)', 'Antora Energy (thermal storage)', 'Skyven Technologies (steam-generating heat pumps)', 'Element 16 (sulfur thermal storage)'],
  'HVAC companies entering industrial → Include if specialized industrial division; Engineering firms with electrification practice → Include if dedicated offering; Heat pump manufacturers with projects → Include if turnkey solutions offered; Thermal storage companies → Include if industrial process focus; Hydrogen vs electric heating → Classify based on primary technology approach',
  ARRAY['Industrial heat pumps', 'high-temperature heat pumps', 'steam-generating heat pumps', 'Electric boilers', 'electrode boilers', 'electric steam generators', 'electric furnaces', 'Process electrification', 'industrial electrification', 'fuel switching', 'decarbonized heat', 'Thermal storage', 'molten salt storage', 'phase change materials', 'thermal batteries', 'Induction heating', 'infrared heating', 'resistance heating', 'electric arc furnace', 'Power-to-heat', 'sector coupling', 'industrial flexibility']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Industry'),
  'Industrial Emissions Management',
  'Companies providing comprehensive solutions for monitoring, reporting, verifying, and physically mitigating industrial emissions including greenhouse gases, air pollutants, and fugitive emissions across industrial facilities.',
  'Reduces industrial emissions through continuous monitoring enabling targeted reduction strategies, regulatory compliance, and physical abatement of emissions at the source, addressing both climate and air quality impacts.',
  ARRAY['Continuous emissions monitoring systems and software', 'Fugitive emissions detection and quantification services', 'Industrial carbon accounting and reporting platforms', 'Emissions control equipment installation and maintenance', 'Methane detection and mitigation services', 'Flare gas recovery and management systems', 'VOC control and recovery services', 'Regulatory compliance software and consulting', 'Integrated monitoring + abatement solutions'],
  ARRAY['Sensor/equipment manufacturing only (without services/systems)', 'General environmental consulting without emissions focus', 'Energy efficiency without emissions focus (→ Industrial Energy Efficiency)', 'Process changes for emissions reduction (→ other relevant themes)', 'Carbon capture and storage (→ would be separate theme if included)', 'Ambient air quality monitoring (→ Air Quality Monitoring & Control)'],
  ARRAY['Qube Technologies (emissions monitoring)', 'SeekOps (methane detection)', 'Kairos Aerospace (aerial monitoring)', 'Envirosuite (environmental intelligence)', 'CleanConnect.ai (emissions management)'],
  'Environmental consulting firms → Include if industrial emissions is primary focus; Oil & gas service companies → Include emissions-specific services only; Software companies with emissions modules → Include if industrial focus is primary; Safety companies adding emissions → Include if emissions becomes major focus; IoT sensor companies → Include only with full solution not just hardware',
  ARRAY['Emissions monitoring', 'continuous emissions monitoring systems (CEMS)', 'stack testing', 'Fugitive emissions', 'leak detection and repair (LDAR)', 'optical gas imaging', 'Carbon accounting', 'GHG reporting', 'emissions inventory', 'Scope 1/2/3', 'Scrubbers', 'selective catalytic reduction (SCR)', 'flue gas desulfurization', 'Methane mitigation', 'flare management', 'vapor recovery', 'emissions capture', 'MRV (monitoring, reporting, verification)', 'emissions compliance', 'air permits']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Agriculture'),
  'Precision Agriculture',
  'Companies manufacturing precision farming equipment and providing data-driven technologies, analytics platforms, and smart farming solutions that optimize agricultural inputs, improve yields, and reduce environmental impact through precise application of resources.',
  'Reduces agricultural emissions and environmental impact by optimizing fertilizer use (reducing N2O emissions), minimizing water consumption, reducing pesticide application, and improving overall farm efficiency through data-driven decision making.',
  ARRAY['Precision agriculture equipment manufacturing (sensors, drones, variable rate application systems)', 'Farm management software and data platforms', 'Variable rate technology and application systems', 'Agricultural drone services and imagery analytics', 'Satellite-based crop monitoring platforms', 'Soil and plant sensors and testing services', 'Weather monitoring and forecasting for agriculture', 'Yield mapping and data analytics', 'Automated irrigation and fertigation systems', 'GPS guidance and auto-steer systems'],
  ARRAY['Traditional farm equipment without precision technology', 'General agricultural consulting without data/tech focus', 'Seed and agrochemical manufacturing', 'Commodity trading and farm finance', 'Food processing and distribution'],
  ARRAY['Farmers Business Network (data platform)', 'Taranis (crop intelligence)', 'Prospera (AI crop monitoring)', 'Granular (farm management software)', 'Trimble Agriculture (precision hardware)'],
  'Equipment manufacturers adding precision → Include if precision becomes core offering; Agribusiness with tech platforms → Include if platform is primary value proposition; Irrigation companies → Include if smart/precision irrigation focused; Weather services → Include if agriculture-specific with actionable insights; Consulting firms → Include only if precision ag technology is core service',
  ARRAY['Precision farming', 'smart farming', 'digital agriculture', 'AgTech', 'farm management software', 'Variable rate application', 'prescription maps', 'yield mapping', 'soil mapping', 'Agricultural IoT', 'farm sensors', 'weather stations', 'soil moisture sensors', 'Satellite imagery', 'drone mapping', 'NDVI', 'multispectral imaging', 'crop monitoring', 'GPS guidance', 'auto-steer', 'section control', 'precision planting', 'Farm data analytics', 'predictive analytics', 'decision support systems']
),
(
  (SELECT id FROM taxonomy_sectors WHERE name = 'Agriculture'),
  'Regenerative Farming',
  'Companies providing services, technologies, and platforms that enable regenerative agricultural practices including carbon farming, soil health improvement, biodiversity enhancement, and holistic farm management that restores ecosystem health.',
  'Reduces agricultural emissions while sequestering carbon by transitioning farms to regenerative practices that improve soil health, enhance biodiversity, and create resilient agricultural systems that function as carbon sinks rather than sources.',
  ARRAY['Regenerative agriculture transition consulting and support', 'Soil carbon measurement and verification services', 'Agricultural carbon credit development and certification', 'Cover crop planning and seed supply services', 'Regenerative practice implementation and training', 'Grazing management and livestock integration services', 'Compost and biological input production', 'Farm ecosystem assessment and planning', 'Regenerative agriculture verification and standards', 'Farmer network platforms for regenerative practices'],
  ARRAY['Conventional agriculture without regenerative practices', 'Pure carbon credit trading without farmer support (→ Natural Capital)', 'Organic certification without regenerative focus', 'Agricultural research without commercialization', 'Land acquisition without practice change support'],
  ARRAY['Indigo Ag (carbon program)', 'Soil Capital (regenerative transition)', 'Fibershed (regional fiber systems)', 'Savory Institute (holistic management)', 'Rodale Institute (research and training)'],
  'Carbon credit developers → Include if providing farmer support services, classify in Natural Capital if just credit trading; Organic farms → Include only if regenerative practices are core (not just organic certification); Ag input companies → Include if biological/regenerative focused; Consulting firms → Include if regenerative agriculture is primary practice; Technology platforms → Include if enabling regenerative practice adoption',
  ARRAY['Regenerative agriculture', 'carbon farming', 'soil health', 'soil organic matter', 'Cover crops', 'no-till', 'conservation tillage', 'crop rotation', 'diverse rotations', 'Holistic management', 'adaptive grazing', 'mob grazing', 'silvopasture', 'Compost', 'biological inputs', 'microbial inoculants', 'vermicompost', 'Agroforestry', 'alley cropping', 'forest farming', 'windbreaks', 'Carbon sequestration', 'soil carbon credits', 'agricultural carbon', 'carbon verification']
);