// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blwwpvvdnpkipjgajwiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsd3dwdnZkbnBraXBqZ2Fqd2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODk1NjQsImV4cCI6MjA3Mjc2NTU2NH0.TcxA_LU9rsihMNT5b5oXmz_tHvekiSUEqVLXxS1nsFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});